ansible_user: ec2-user
ansible_password: DevOps321

MONGODB_HOST: mongodb.lokesh23.online
REDIS_HOST: redis.lokesh23.online
MYSQL_HOST: mysqldb.lokesh23.online 
RABBITMQ_HOST: rabitmq.lokesh23.online 
CATALOGUE_HOST: catalogue.lokesh23.online
USER_HOST: user.lokesh23.online
CART_HOST: cart.lokesh23.online
SHIPPING_HOST: shipping.lokesh23.online
PAYMENT_HOST: payment.lokesh23.online