[local]
localhost

[mongodb]
mongodb.lokesh23.online

[redis]
redis.lokesh23.online

[mysql]
mysqldb.lokesh23.online

[rabitmq]
rabitmq.lokesh23.online

[catalogue]
catalogue.lokesh23.online

[user]
user.lokesh23.online

[cart]
cart.lokesh23.online

[shipping]
shipping.lokesh23.online

[payment]
payment.lokesh23.online

[frontend]
frontend.lokesh23.online