# configuring the mongodb server using the ansible 

- name: configuring the mongodb server
  hosts: mongodb
  become: yes
  
  tasks:
  - name: Setup the MongoDB repo file
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB packages
    package:
      name: mongodb-org
      state: present

  - name: Replace a specific configuration line
    replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Enable and start MongoDB service
    service:
      name: mongod
      state: started
      enabled: yes
