- name: configuring the rabbitmq server
  hosts: rabitmq
  become: yes

  tasks:
  - name: Setup the MongoDB repo file
    copy:
      src: rabitmq.repo
      dest: /etc/yum.repos.d/rabitmq.repo
  
  - name: installing the rabitmq server
    package:
      name: rabitmq-server
      state: present
  
  - name: enable and start the service
    service:
      name: rabitmq-server
      state: started
      enabled: true

  - name: creating the user for rabitmq
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      state: present