- name: configuring the catalogue service
  hosts: catalogue
  become: yes

  tasks:
  - name: enable the nodejs:20 module
    command: dnf module enable nodejs:20 -y
  
  - name: install and enable the nodejs
    package:
      name: nodejs
      state: present

  - name: creating the system user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: removing the app directly 
    file:
      path: /app
      state: absent
  
  - name: removing the unzip file for catalogue
    file:
      path: /tmp/catalogue.zip
      state: absent

  - name: creating the app directory 
    file:
      path: /app
      state: directory

  - name: Download a file from a URL
    get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: "/tmp/catalogue.zip"

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: Install npm package.
    community.general.npm:
      path: /app

  - name: copy the files in catalogue 
    ansible.builtin.template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy mongo repo 
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    package:
      name: mongodb-mongosh
      state: present
  
  - name: check catalogue schema exist ot not
    shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags:
    - mongodb

  - name: print catalogue_output
    debug: 
      msg: "{{ catalogue_output }}"
    tags:
    - mongodb

  - name: load products
    shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    tags:
    - mongodb

  - name: deamon reload
    systemd_service:
      name: catalogue
      daemon_reload: true

  - name: enable and start catalogue
    service:
      name: catalogue
      state: restarted
      enabled: yes

